### ISSUE TITLE
Automate deployment of demo gallery

### ISSUE THREAD

**Issue by wwwillchen** [google/mesop#896]
We can use GitHub actions and have a label specifically for deploying demo / whenever a new version is cut:

```
name: Deploy on Merge

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'deploy')
    steps:
 ```
